name: Run Jupyter Notebook with Secret

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  execute-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install notebook nbconvert python-dotenv

      - name: Set up environment
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Execute Jupyter Notebook
        run: |
          python -m nbconvert --to notebook --execute --inplace Data_Extraction.ipynb
